# Number of days of inactivity before an issue becomes stale
daysUntilStale: 0
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 0
# Label to use when marking an issue as stale
staleLabel: wontfix
closeComment: false
