test:
  image: ubuntu:disco
  script:
  - apt-get update -qy
  - apt-get install -y python3-pip tor
  - pip3 install --require-hashes -r requirements.txt
  - pip3 install --require-hashes -r requirements-notifications.txt
  - python3 --version
  - make test
