BOOTSTRAP_ATTEMPTS = 5
PEER_AMOUNT_TO_ASK = 3
TRANSPORT_SIZE_BYTES = 64
BLOCK_MAX_SIZE = 1024 * 2000
BLOCK_ID_SIZE = 128
DANDELION_EPOCH_LENGTH = 120

# Magic number i made up, not really specified in dandelion++ paper
MAX_INBOUND_DANDELION_EDGE = 50  # Mainly picked to avoid slowloris

# Dandelion subgraph is aprox 4-regular
OUTBOUND_DANDELION_EDGES = 2

MAX_STEM_BLOCKS_PER_STREAM = 1000
BLACKHOLE_EVADE_TIMER_SECS = DANDELION_EPOCH_LENGTH * 3