#!/bin/sh

set -e

[ "root" != "$USER" ] && exec sudo $0 "$@"

export OUTPUT_DIR=${OUTPUT_DIR:=/usr/share/onionr}
export ONIONR_HOME=${ONIONR_HOME:=/etc/onionr}
export LOG_DIR=${LOG_DIR:=/var/log/onionr}

cd "$OUTPUT_DIR/onionr"

command="python3.7 onionr.py '$@'"
echo $command
exec su onionr -s /bin/sh -c "$command"
